### ISSUE TITLE
The usage of srand is incorrect

### ISSUE THREAD

**Issue by Ruide** [GHamrouni/Recommender#10]
the generate_random_matrix is using srand(0) to generate random number everytime.

srand(0) sets the seed of the random number generator to 0. Calling it again with the same parameter sets the seed to 0 again, and will cause the random generator to create the same output.

e.g.
    srand(0);
    for(int i = 0; i<5; i++)
        printf(" %d ", rand());    
    return 0;

prints  1804289383  846930886  1681692777  1714636915  1957747793 all the time (should use something like srand(time(0)))

So the matrix is not generated randomly as it should be.

**Comment by GHamrouni** [comment]
@Ruide thank you for the comment, the generate random matrix code has a parameter for setting the seed.
In order to modify the default seed 

```
double** generate_random_matrix(int nrow,int ncol,int seed);
```
In order to modify the default seed you can set the value in the model parameters :
```
struct model_parameters
{
	size_t			users_number;
	size_t			items_number;

	size_t			dimensionality; /* dimensionality of the joint latent factor space */
	size_t			iteration_number;

	size_t			training_set_size;  /* The number of known ratings */

	float			lambda;          /* The constant lambda controls the extent of regularization */
	float			step;            /* step size in stochastic gradient descent algorithm */

	float			step_bias;
	float			lambda_bias;

	int				algoithm_type;

	int 			seed;
	int 			bin_width;
	int 			proj_family_size;
	float			betha;
};
```

**Comment by Ruide** [comment]
Yes, the seed should be set as a random number. 

In the test.c file, the example usage does not include the setting up of random seed. So in the example, the seed is default as 0 and matrix will always start with same initial value.

But I guess it won't matter much in terms of learning efficiency anyway.

**Comment by GHamrouni** [comment]
@Ruide thanks, I will update the test files, it makes sense to setup the seed in the exemple.
Feel free also to make pull request.
